# Generated by Django 4.1.3 on 2022-11-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='today_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='today_looked',
            field=models.IntegerField(default=0),
        ),
    ]
