# Generated by Django 4.1.3 on 2022-11-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_imagemodel_today_good_imagemodel_today_looked'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='hour_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='hour_looked',
            field=models.IntegerField(default=0),
        ),
    ]
