# Generated by Django 4.1.3 on 2022-11-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_commentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='tag0',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag9',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='server.imagemodel'),
        ),
    ]
