# Generated by Django 4.1.3 on 2022-11-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_imagemodel_tag0_imagemodel_tag1_imagemodel_tag2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='ai_model',
            field=models.CharField(default='MovelAI', max_length=30),
        ),
    ]
