# Generated by Django 4.1.3 on 2022-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_imagemodel_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='ai_model',
            field=models.CharField(default='NovelAI', max_length=30),
        ),
    ]
