# Generated by Django 4.1.3 on 2022-11-25 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_imagemodel_is_archived_alter_imagemodel_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('good', models.IntegerField(default=0)),
                ('today_looked', models.IntegerField(default=0)),
                ('today_good', models.IntegerField(default=0)),
                ('hour_looked', models.IntegerField(default=0)),
                ('hour_good', models.IntegerField(default=0)),
                ('tag0', models.CharField(max_length=30, null=True)),
                ('tag1', models.CharField(max_length=30, null=True)),
                ('tag2', models.CharField(max_length=30, null=True)),
                ('tag3', models.CharField(max_length=30, null=True)),
                ('tag4', models.CharField(max_length=30, null=True)),
                ('tag5', models.CharField(max_length=30, null=True)),
                ('tag6', models.CharField(max_length=30, null=True)),
                ('tag7', models.CharField(max_length=30, null=True)),
                ('tag8', models.CharField(max_length=30, null=True)),
                ('tag9', models.CharField(max_length=30, null=True)),
                ('ai_model', models.CharField(default='NovelAI', max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('prompt', models.TextField(default='入力されていません')),
                ('neg_prompt', models.TextField(default='入力されていません')),
                ('additonal_tags', models.TextField(default='入力されていません')),
                ('seed', models.IntegerField(default=-1)),
                ('MotoImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.imagemulmodel')),
            ],
        ),
    ]
