# Generated by Django 4.1.3 on 2022-11-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_specificimagemodel_motoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificimagemodel',
            name='additonal_tags',
        ),
    ]
