# Generated by Django 4.1.3 on 2022-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_specificimagemodel_additonal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulmodel',
            name='additonal_tags',
            field=models.TextField(default='入力されていません'),
        ),
    ]
