# Generated by Django 4.1.3 on 2022-11-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_imagemulmodel_additonal_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemulmodel',
            old_name='description',
            new_name='decription',
        ),
    ]
