# Generated by Django 4.1.3 on 2022-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_rename_description_imagemulmodel_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulmodel',
            name='is_nsfw',
            field=models.IntegerField(default=0),
        ),
    ]
